pair = ["ETH",
        "ADA",
        "ATOM",
        "AVAX",
        "BNB",
        "BTC",
        "DOT",
        "FTM",
        "GALA",
        "ICP",
        "LTC",
        "MANA",
        "SOL",
        "XRP",
        "ALGO"
        ]
